name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write  # This is required for OIDC authentication
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Load environment variables
        run: |
          echo "Loading environment variables from .env file"
          if [ -f .env ]; then
            export $(cat .env | grep -v '#' | awk '/=/ {print $1}')
          fi

      - name: Install dependencies
        run: npm ci
        
      - name: Create .env.production file
        run: |
          cat > .env.production << EOL
          VITE_API_URL=${{ secrets.VITE_API_URL || 'https://api.yourapp.com' }}
          VITE_APP_ENV=production
          VITE_APP_TITLE=${{ secrets.VITE_APP_TITLE || 'Expense Tracker' }}
          VITE_AZURE_STORAGE_ACCOUNT=${{ secrets.VITE_AZURE_STORAGE_ACCOUNT || 'sultaneng' }}
          VITE_AZURE_CONTAINER=${{ secrets.VITE_AZURE_CONTAINER || 'sultangengwebsite' }}
          VITE_AZURE_SAS_TOKEN=${{ secrets.VITE_AZURE_SAS_TOKEN }}
          VITE_AZURE_BASE_URL=${{ secrets.VITE_AZURE_BASE_URL || 'https://sultaneng.blob.core.windows.net/sultangengwebsite' }}
          EOL

      - name: Build
        run: npm run build

      - name: Create zip for deployment
        run: |
          cp web.config dist/
          cp .env.production dist/.env
          cd dist
          zip -r ../node-app.zip *

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip node-app.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure correct Azure Subscription
        run: |
          echo "🔄 Setting Azure Subscription..."
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          echo "✅ Successfully set Azure subscription!"
          az account show --output table

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .

      - name: Configure Azure Web App settings
        uses: azure/cli@v1
        with:
          inlineScript: |
            echo "🔧 Configuring Azure Web App settings..."
            az webapp config appsettings set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings \
              VITE_AZURE_STORAGE_ACCOUNT=${{ secrets.VITE_AZURE_STORAGE_ACCOUNT }} \
              VITE_AZURE_CONTAINER=${{ secrets.VITE_AZURE_CONTAINER }} \
              VITE_AZURE_SAS_TOKEN=${{ secrets.VITE_AZURE_SAS_TOKEN }} \
              VITE_AZURE_BASE_URL=${{ secrets.VITE_AZURE_BASE_URL }} \
              VITE_APP_ENV=production
            echo "✅ Azure Web App settings configured successfully."
